"""Emit SQL that replaces `panel` and `countries` and appends the current month's advisories.

The panel cannot be appended to: the anchor year moving forward rewrites every historical
value, so it is replaced wholesale inside a transaction. Advisory observations are additive,
so the current month is inserted with OR IGNORE and a rerun is a no-op.
"""

from __future__ import annotations

import argparse
import datetime
import subprocess
import sys
from pathlib import Path

import pandas as pd

from real_travel_cost.countries import CANONICAL_NAMES, attach_country_codes, canonicalize_names
from real_travel_cost.metrics import _anchor_year
from real_travel_cost.pipeline import load_panel
from real_travel_cost.sources import fetch_price_level_index, fetch_travel_advisories

PANEL_COLUMNS = [
    "country_code",
    "date",
    "advisory_level",
    "current_dollars",
    "price_level_nowcast",
    "cpi",
    "exr",
    "relative_prices",
]

# A parse regression shows up as a collapse in country count, not a plausible small drift.
MIN_COUNTRIES = 150
MAX_CURRENT_DOLLARS = 1.5


def _num(value) -> str:
    return "NULL" if pd.isna(value) else repr(round(float(value), 6))


def _str(value) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)) or value == "":
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def _git_sha() -> str | None:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True, check=True
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def check(panel: pd.DataFrame) -> list[str]:
    """Invariants that must hold before anything is written; see CLAUDE.md."""
    problems = []
    countries = panel.country_code.nunique()
    if countries < MIN_COUNTRIES:
        problems.append(f"only {countries} countries, expected >= {MIN_COUNTRIES}")

    us = panel.loc[panel.country_code == "USA", "current_dollars"]
    if us.empty:
        problems.append("USA missing from the panel")
    elif not us.round(6).eq(1.0).all():
        problems.append(f"USA is not exactly 1.0 (min {us.min()}, max {us.max()})")

    latest = panel.sort_values("date").groupby("country_code").tail(1)
    hot = latest.loc[latest.current_dollars > MAX_CURRENT_DOLLARS]
    if not hot.empty:
        worst = hot.nlargest(1, "current_dollars").iloc[0]
        problems.append(
            f"{len(hot)} countries above {MAX_CURRENT_DOLLARS} "
            f"(worst {worst.country_code} at {worst.current_dollars:.2f}) — likely a unit mismatch"
        )
    return problems


def country_rows(panel: pd.DataFrame, price_level: pd.DataFrame) -> list[tuple[str, str, str]]:
    """Code -> display name, flagged by whether CANONICAL_NAMES overrode the World Bank label."""
    names = price_level[["country_code", "country_name"]].drop_duplicates("country_code")
    keep = names.loc[names.country_code.isin(panel.country_code.unique())]
    return [
        (
            r.country_code,
            r.country_name,
            "canonical" if r.country_code in CANONICAL_NAMES else "worldbank",
        )
        for r in keep.itertuples()
    ]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=Path("db/publish.sql"))
    ap.add_argument("--refresh", action="store_true", help="refetch upstream instead of caching")
    ap.add_argument("--batch", type=int, default=500)
    ap.add_argument("--skip-advisories", action="store_true", help="panel and countries only")
    args = ap.parse_args()

    panel = load_panel(refresh=args.refresh)
    price_level = canonicalize_names(fetch_price_level_index())

    problems = check(panel)
    if problems:
        for p in problems:
            print(f"FAIL: {p}", file=sys.stderr)
        sys.exit(1)

    month = pd.Timestamp.today().normalize().replace(day=1).strftime("%Y-%m-01")
    lines = ["-- Generated by scripts/publish_d1.py; do not edit.", "BEGIN;"]

    lines.append("DELETE FROM countries;")
    rows = country_rows(panel, price_level)
    for start in range(0, len(rows), args.batch):
        values = ",\n  ".join(
            f"({_str(c)}, {_str(n)}, '{s}')" for c, n, s in rows[start : start + args.batch]
        )
        lines.append(f"INSERT INTO countries (country_code, name, source) VALUES\n  {values};")

    lines.append("DELETE FROM panel;")
    out = panel[PANEL_COLUMNS].copy()
    out["date"] = pd.to_datetime(out.date).dt.strftime("%Y-%m-01")
    records = list(out.itertuples(index=False))
    for start in range(0, len(records), args.batch):
        values = ",\n  ".join(
            f"({_str(r.country_code)}, '{r.date}', {_num(r.advisory_level)}, "
            f"{_num(r.current_dollars)}, {_num(r.price_level_nowcast)}, "
            f"{_num(r.cpi)}, {_num(r.exr)}, {_num(r.relative_prices)})"
            for r in records[start : start + args.batch]
        )
        lines.append(f"INSERT INTO panel ({', '.join(PANEL_COLUMNS)}) VALUES\n  {values};")

    advisory_count = 0
    feed = {}
    if not args.skip_advisories:
        fetched = fetch_travel_advisories()
        feed = dict(fetched.attrs)
        advisories = attach_country_codes(fetched, price_level)
        advisories.attrs.update(feed)
        advisories = advisories.dropna(subset=["country_code"]).drop_duplicates("country_code")
        observed_at = advisories.attrs.get("observed_at")
        values = ",\n  ".join(
            f"({_str(r.country_code)}, '{month}', {int(r.advisory_level)}, "
            f"{_str(r.issued)}, {_str(observed_at)}, 'rss')"
            for r in advisories.itertuples()
        )
        lines.append(
            "INSERT OR IGNORE INTO advisory_observations"
            " (country_code, month, level, issued, observed_at, source)"
            f" VALUES\n  {values};"
        )
        advisory_count = len(advisories)

    built_at = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    lines.append(
        "INSERT INTO build_meta (built_at, anchor_year, panel_rows, countries, latest_month,"
        " git_sha, feed_last_modified, feed_bytes, feed_reads)"
        f" VALUES ('{built_at}', {_anchor_year(panel, price_level)}, {len(panel)},"
        f" {panel.country_code.nunique()}, '{out.date.max()}', {_str(_git_sha())},"
        f" {_str(feed.get('feed_last_modified'))}, {feed.get('feed_bytes') or 'NULL'},"
        f" {feed.get('feed_reads') or 'NULL'});"
    )
    lines.append("COMMIT;")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"panel {len(panel)} rows, {panel.country_code.nunique()} countries")
    print(f"countries {len(rows)}, advisories {advisory_count} for {month}")
    print(f"wrote {args.out} ({args.out.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
