"""Load the Wayback-derived advisory history into `advisory_observations`, once.

`build_advisory_history.py` reconstructed 2018-03 onward from Internet Archive captures and
wrote interval rows. This expands those intervals back into one observation per country-month
and emits SQL, after which the ongoing RSS job extends the same table and Wayback is no longer
needed. See docs/advisory-history.md.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

import pandas as pd

from real_travel_cost.countries import attach_country_codes, canonicalize_names
from real_travel_cost.sources import fetch_price_level_index


def _sql_str(value: str | None) -> str:
    return "NULL" if value in (None, "") else "'" + value.replace("'", "''") + "'"


def expand(rows: list[dict], codes: dict[str, str], last_month: str) -> list[dict]:
    """Interval rows -> one observation per country-month, dropping unmappable names."""
    months = pd.date_range("2018-03-01", last_month, freq="MS").strftime("%Y-%m-01")
    out: dict[tuple[str, str], dict] = {}
    for row in rows:
        code = codes.get(row["name"])
        if not code:
            continue
        end = row["valid_to"] or months[-1]
        for month in months:
            if row["valid_from"] <= month <= end:
                # Intervals for one code never overlap, so first write wins uncontested.
                out.setdefault(
                    (code, month),
                    {
                        "country_code": code,
                        "month": month,
                        "level": int(row["level"]),
                        "issued": row["issued"],
                    },
                )
    return [out[k] for k in sorted(out)]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--csv", type=Path, default=Path("data/advisory_history.csv"))
    ap.add_argument("--out", type=Path, default=Path("db/seed_advisory_observations.sql"))
    ap.add_argument("--last-month", default="2026-08-01", help="last month to expand into")
    ap.add_argument("--batch", type=int, default=500, help="rows per INSERT statement")
    args = ap.parse_args()

    if not args.csv.exists():
        sys.exit(f"{args.csv} not found; it is the only parsed copy of the Wayback history")

    rows = list(csv.DictReader(args.csv.open()))
    reference = canonicalize_names(fetch_price_level_index())
    names = sorted({r["name"] for r in rows})
    mapped = attach_country_codes(pd.DataFrame({"country_name": names}), reference)
    codes = {
        r.country_name: r.country_code for r in mapped.itertuples() if pd.notna(r.country_code)
    }

    observations = expand(rows, codes, args.last_month)
    dropped = sorted(set(names) - set(codes))
    print(f"{len(names)} names -> {len(codes)} codes, {len(dropped)} dropped")
    print(f"{len(rows)} intervals -> {len(observations)} observations")
    print(f"dropped: {', '.join(dropped[:8])}{' ...' if len(dropped) > 8 else ''}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w") as f:
        f.write("-- Generated by scripts/seed_advisory_history.py; run once.\n")
        for start in range(0, len(observations), args.batch):
            chunk = observations[start : start + args.batch]
            values = ",\n  ".join(
                f"('{o['country_code']}', '{o['month']}', {o['level']}, "
                f"{_sql_str(o['issued'])}, NULL, 'wayback')"
                for o in chunk
            )
            f.write(
                "INSERT OR IGNORE INTO advisory_observations"
                " (country_code, month, level, issued, observed_at, source) VALUES\n  "
                f"{values};\n"
            )
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
